### ISSUE TITLE
Gender not being parsed

### ISSUE THREAD

**Issue by newswim** [open-austin/azure-indigent-defense#37]
It looks like the `gender` field isn't showing up in the output data.

CC @emilyrbartha

**Comment by tpadmanabhan** [comment]
Re-assign this ticket. Validate if needed, then priority and size with Nick and Nidhi

**Comment by tpadmanabhan** [comment]
@newswim Nick needs this dataset

**Comment by normaljosh** [comment]
Just confirmed that gender is not in the current jsons being extracted

this would probably be a good thing for @nicolassaw to first work on when learning the parser

**Comment by normaljosh** [comment]
nvm it's just called sex
