### ISSUE TITLE
Include "county" in result set

### ISSUE THREAD

**Issue by newswim** [open-austin/azure-indigent-defense#52]
As we start expanding to more counties, things like Case Number are not actually unique across counties. Concretely, you might see case number ABC-123 in two different counties, but they refer to completely different cases.

**Comment by tpadmanabhan** [comment]
Low priority

**Comment by tpadmanabhan** [comment]
@newswim Dan, can you get @nicolassaw access to the dataset referenced here?

**Comment by tpadmanabhan** [comment]
this may also be necessary in the filename if we aren't already doing this
if it's already in filename and in the json itself, this can be set to done imo

**Comment by tpadmanabhan** [comment]
@nicolassaw can confirm this by looking at the cosmos db data

**Comment by nicolassaw** [comment]
Committed the small code needed for this to the parser code in the indigent-defense-stats repo.

https://github.com/open-austin/indigent-defense-stats/pull/64
