### ISSUE TITLE
Clean up data in "Evidence of Representation" chart

### ISSUE THREAD

**Issue by newswim** [open-austin/azure-indigent-defense#53]
Cases that are _dismissed_ should not be included in the Evidence of Representation data set.

This might be blocked by having Outcomes. Because we need to know about dismissal.

@nicolassaw or Nate can expand on this.

**Comment by nathanfennell** [comment]
This isn't quite right. We want to include most dismissals. We want to at least consider whether we should remove cases that are dismissed very quickly, before any defense lawyer would have done any work on the case, such as cases where the police obviously made a bad arrest. So we want to look at every case that was dismissed within a short period of time from the first date with any entry (maybe within 2 days of the offense date?) to see if that meaningfully changes the percentage of cases with significant motions filed.

**Comment by tpadmanabhan** [comment]
Review with Nick and Nidhi on 3/31

**Comment by tpadmanabhan** [comment]
@nicolassaw recommends including all cases in dataset

**Comment by tpadmanabhan** [comment]
@newswim Dan, is this completed?

**Comment by nicolassaw** [comment]
I am going to close this. This was a ticket to remove cases from visualization dataset where the case was dismissed quickly. It is difficult to know from the record whether it was fast advocacy or the independent decision of the state to dismiss. I recommend keeping them all. In many jurisdictions, where there is a fast rejection, they do not appoint altogether. So, this pattern may already pull out instances where the attorney may not have done work on the case where there was a rejected case.
