### ISSUE TITLE
Document Azure infrastructure and services

### ISSUE THREAD

**Issue by newswim** [open-austin/azure-indigent-defense#57]
Needed:
* [x] Few sentences - why we are moving away from the serverless approach
* [x] List of key points - how to onboard a new dev to develop the "cron job on VM" approach. 
* [x] Artifact - In [this xls](https://docs.google.com/spreadsheets/d/11qsWz7nn7gicxzeKCnSs-PkiWX3Zs4pStgd3plcRzrQ/edit?pli=1#gid=0) fill in expected result of the scrapers (where they write to, and what the data should look like"
* [x] Artifact - Visualize the containers by adding onto [Pipeline flowchart](https://docs.google.com/presentation/d/16Mj4gGEDedUP1Q3g5M99lcUhe479eibX/edit#slide=id.p1)

**Comment by newswim** [comment]
Add Raj and Dima once they provide GH usernames.

**Comment by newswim** [comment]
Blocks open-austin/indigent-defense-stats#79

**Comment by geworfenheit** [comment]
Dan had intended to work on the filtered down list of priorities for documentation on 4-14-24. I reminded him day of but he was unable to do work on this. He is currently loaded up on his employment tasks and said it will be a "bit of time" before he can look into the priorities for documentation.

I will follow-up with him on the exact timeframe as well as reminders.

**Comment by tpadmanabhan** [comment]
@geworfenheit Following up with @newswim

**Comment by tpadmanabhan** [comment]
@normaljosh to reach out to Lucia

**Comment by tpadmanabhan** [comment]
Hi @normaljosh @newswim @zimzoom, please update this ticket per your 4/28 meeting. Thanks

**Comment by tpadmanabhan** [comment]
@normaljosh @newswim Thanks Josh. We have the updated doc
