### ISSUE TITLE
Use a "Logic App" to orchestrate function calls

### ISSUE THREAD

**Issue by newswim** [open-austin/azure-indigent-defense#6]
The idea for logic apps is that we'll be able to call the Scraper and Parser functions with arguments based on some "logic" that we "write".

https://learn.microsoft.com/en-us/azure/logic-apps/logic-apps-overview

**Comment by zimzoom** [comment]
Update: we are now running a Logic App on the prod environment only, for cost savings; and so far only 1 workflow which is past 5 years, all JOs.

**Comment by tpadmanabhan** [comment]
Validate with Josh L if needed, then determine priority and size

**Comment by tpadmanabhan** [comment]
This will not be done, new architecture will be on Azure Virtual Machine
